import type { Metadata } from "next";
import "./globals.css";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import { Navbar } from "@/components/ui/navbar";
import { PageLoader } from "@/components/ui/page-loader";

import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ErrorReporter />
        <PageLoader />
        <Navbar />
      </body>
    </html>
  );
}